---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:
  - name: start service
    service:
      name: httpd
      state: stopped
  - name: installing httpd
    yum:
      name: httpd
      state: absent


