---
- name: My playbook for jenkins installation
  hosts: all
  become: true
  tasks: 
  - name: Install Jav
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Add Jenkins repository key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: Add Jenkins repository
    yum_repository:
      name: jenkins
      description: Jenkins Repository
      baseurl: https://pkg.jenkins.io/redhat-stable
      gpgcheck: yes
      state: present
  - name: Install Jenkins
    yum:
      name: jenkins
      state: present
  - name: Start Jenkins service
    systemd:
      name: jenkins
      state: started
      enabled: yes      
