---
- name: My packages plabook
  hosts: all
  become: true
  tasks:
  - name: install http 
    yum:
      name: http
      state: installed
    ignore_errors: yes

  - name: install multiple packages
    yum:
      name:
        - git
        - docker
        - tree
        - mysql
      state: installed
